FROM condaforge/mambaforge:latest AS conda

COPY illumina.environment.yml ./environment.yml

RUN /opt/conda/bin/mamba env create -f /environment.yml

ENV PATH=/opt/conda/envs/artic_rsv_illumina/bin:$PATH

CMD ["/bin/bash"]